@base_url = http://localhost:3003

POST {{base_url}}/user HTTP/1.1
Content-Type: application/json

{}

###

POST {{base_url}}/stock HTTP/1.1
Content-Type: application/json

{}

###
POST {{base_url}}/penjualan HTTP/1.1
Content-Type: application/json

{}

###

POST {{base_url}}/accounting HTTP/1.1
Content-Type: application/json

{}

###

POST {{base_url}}/login HTTP/1.1
Content-Type: application/json

{
    "NIK": 207006056,
    "password": 12383125
}

###

POST {{base_url}}/inputAccounting HTTP/1.1
Content-Type: application/json

{ 
    "kode_transaki": 546546,
    "debit": 13471282,
    "credit" : 12545,
    "deskripsi" : "Bangsat aokwoakwo",
    "transaksi_date": "2020-05-04 07:15:24"
}

###

POST {{base_url}}/changeAccounting HTTP/1.1
Content-Type: application/json

{
    "kode_transaki": 546546,
    "debit": 13471282,
    "credit" : 12545,
    "deskripsi" : "Meki fajri"
}

###

POST {{base_url}}/inputPenjualan HTTP/1.1
Content-Type: application/json

{ 
    "kode_penjualan": 722312,
    "kode_barang": 13471282,
    "total_per_barang" : 12,
    "harga_per_barang" : 25000,
    "total_harga" : 300000,
    "qty" : 21,
    "transaksi_date": "2020-05-04 07:15:24"
}

###

POST {{base_url}}/changePenjualan HTTP/1.1
Content-Type: application/json

{
    "kode_barang": 13471282,
    "total_per_barang" : 6,
    "harga_per_barang" : 20000,
    "total_harga" : 120000,
    "qty" : 15
}

###

POST {{base_url}}/deletePenjualan HTTP/1.1
Content-Type: application/json

{
    "kode_barang": 13471282
} 

###

POST {{base_url}}/inputStock HTTP/1.1
Content-Type: application/json

{
    "kode_barang": 13471282,
    "nama_barang": "pork yang halal",
    "harga" : 56000,
    "qty" : 21,
    "transaksi_date" : "2020-07-05 02:15:59",
    "expired_date": "2022-07-05 02:15:59"
}

###

POST {{base_url}}/changeStock HTTP/1.1
Content-Type: application/json

{
    "kode_barang": 3,
    "nama_barang": "fajri babi",
    "harga" : 100000,
    "qty" : 21
}

###

POST {{base_url}}/deleteStock HTTP/1.1
Content-Type: application/json

{
    "kode_barang": 13471282
} 

###

POST {{base_url}}/inputUser HTTP/1.1
Content-Type: application/json

{
    "NIK": 207006056,
    "nama": "Al fajri",
    "jenis_kelamin" : "l",
    "agama" : "islam",
    "jabatan" : "hansip",
    "password": 12383125
}

###
POST {{base_url}}/changeUser HTTP/1.1
Content-Type: application/json

{
    "NIK": 207006056,
    "password": 2147483647,
    "jabatan" : "Rukun warga"
}

###
POST {{base_url}}/deleteUser HTTP/1.1
Content-Type: application/json

{
    "NIK": 2
} 